version: 2.1
jobs:
  tests:
    docker:
      - image: node:12.18
    steps:
      - checkout
      - run: yarn --frozen-lockfile --non-interactive && yarn test && yarn tsc
  publish:
    docker:
      - image: node:12.18
    steps:
      - checkout
      # build
      - run: yarn --frozen-lockfile --non-interactive && yarn tsc
      # Auth
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_TOKEN" >> .npmrc
      # update package version
      - run: npm version --no-git-tag-version $CIRCLE_TAG
      # push to npm
      - run: npm publish

workflows:
  version: 2
  mortgage-helpers:
    jobs:
      - tests
      - publish:
          filters:
            tags:
              only: /^[0-9.]+$/
            branches:
              ignore: /.*/
